config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'search', to: "carparks#search", as: :search
  resources :bookings, except: [:create]
  resources :carparks do
    resources :reviews, only: [:new, :create, :index]
    resources :bookings, only: [:create]
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :carpark

  has_many :reviews, dependent: :destroy

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/carpark.rb
class Carpark < ApplicationRecord
  belongs_to :user, required: false
  has_many :bookings
  has_many :users, through: :bookings
  has_many :reviews, through: :bookings
  validates :address, presence: true
  # validates :length, :width, :height, :rate_day, presence: true
  validates :rate_day, numericality: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :carparks
  has_many :reviews, through: :bookings

  validates :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_booking, only: [:edit, :update,:destroy]

  def index
    @today_date = Date.today
    @bookings = current_user.bookings.where("start_date >= ?", @today_date).sort_by { |day| day[:start_date] }
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @carpark = Carpark.find(params[:carpark_id])
    total_day = (@booking.end_date - @booking.start_date).to_f.ceil
    @total_price = @carpark.rate_day * total_day

    @booking.user = current_user
    @booking.carpark = @carpark
    @booking.total_price = @total_price
    if @booking.save
      redirect_to bookings_path
    else
      render "carparks/show"
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    if @booking.save
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(
      :user_id,
      :carpark_id,
      :start_date,
      :end_date,
      :total_price
    )
  end
end

app/controllers/carparks_controller.rb
class CarparksController < ApplicationController
  before_action :set_carpark, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :search]

  def index
    @carparks = Carpark.all

    @markers = @carparks.map do |carpark|
      {
        lat: carpark.latitude,
        lng: carpark.longitude,
        id: carpark.id,
        address: carpark.address
      }
    end
  end

  def search
    # @carparks = Carpark.where("address ILIKE ?", "%#{params[:query]}%") 
    @carparks = Carpark.near(params[:query], 10)      # venues within 10 km of Tour Eiffel
    @start_date = (params[:date][:start_date]).to_date
    @end_date = (params[:date][:end_date]).to_date
    @bookings = Booking.where(carpark_id: @carparks.each.pluck(:id))

    if @bookings.any?
      @bookings.each do |booking|
        if booking.end_date >= @start_date && @end_date >= booking.start_date
          @carparks = @carparks.where("id != :id", id: booking.carpark.id)
        end
      end
    end

    @markers = @carparks.map do |carpark|
      {
        lat: carpark.latitude,
        lng: carpark.longitude,
        id: carpark.id,
        address: carpark.address
      }
    end
  end

  def show
    @booking = Booking.new
    @reviews = @carpark.reviews
  end

  def new
    @carpark = Carpark.new
  end

  def create
    @carpark = Carpark.new(carpark_params)
    if @carpark.save
      redirect_to carpark_path(@carpark)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @carpark.update(carpark_params)
    redirect_to carpark_path(@carpark)
  end

  def destroy
    @carpark.destroy
    redirect_to carparks_path
  end

  private

  def set_carpark
    @carpark = Carpark.find(params[:id])
  end

  def carpark_params
    params.require(:carpark).permit(
      :user_id,
      :average_rating,
      :length,
      :width,
      :height,
      :latitude,
      :longitude,
      :rate_day,
      :address,
      :photo
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show]

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(
      :content,
      :rating
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<br>
<div class ="container mt-5 pt-5">
  <div class ="row">

    <div class="col-lg-8">
      <div class="card-trip">
      <img src=<%= @booking.carpark.photo %>>
        <div class="card-trip-infos">
          <div>
            <h2><%=@booking.carpark.address %></h2>
            <p>Length: <%=@booking.carpark.length %>cm x
              Width: <%=@booking.carpark.width %>cm x
              Height: <%=@booking.carpark.height %>cm</p>
          </div>
          <h2 class="card-trip-pricing">Rate Per Day: $<%=@booking.carpark.rate_day%></h2>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="card-product-infos booking-form-card" id='carpark-booking-dates' data-unavailable="<%= @booking.carpark.unavailable_dates.to_json %>">
        <%= simple_form_for  @booking do |f| %>
          <h3 class="pt-3">Booking:</h3>
          <%= f.input :start_date, as: :string, type: :text, class: "form-control", placeholder: "Select your start date" %>
          <%= f.input :end_date, as: :string, type: :text, class: "form-control", placeholder: "Select your end date" %>
          <% if user_signed_in? %>
            <% if current_user.id != @booking.carpark.user_id  %>
              <%= f.submit "Reserve now", class: "btn btn-outline-success mt-5"%>
            <% else %>
              <%= link_to "My Dashboard", bookings_path, class: "btn btn-outline-success mt-5" %>
            <% end %>
          <% else %>
            <%= f.submit "Reserve now", class: "btn btn-outline-success mt-5"%>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <div>
  <%= link_to "Make a new booking", root_path, class: "btn btn-primary btn-sm" %>
  </div>
  <%= link_to "Back to my bookings", bookings_path, class: "btn btn-primary btn-sm" %>
  </div>
  <div>
</div>

app/views/bookings/index.html.erb
<div class="banner-bookings">
  <div class="container">
    <h1 class="head text-center my-5 py-5">Upcoming Bookings</h1>
  </div>
</div>
<div class="container my-5">
  <div class="col-md-10 mt-5 mx-auto">
    <% @bookings.each do |booking| %>
      <div class="card-product">
        <img src=<%= booking.carpark.photo %> />
        <div class="card-product-booking-infos">
          <% if booking.start_date > @today_date %>
            <p class="my-2" id="remaining_days">
              <%= (booking.start_date - @today_date).to_f.ceil %>
              days left
            </p>
          <% else %>
            <p class="mb-1 mt-2" id="remaining_days">
              Ongoing booking
            </p>
          <% end %>
          <h2 id="booking-link"><%= link_to booking.carpark.address, edit_booking_path(booking) %></h2>
          <p class="mb-2 mt-1">Booking date: <%= booking.start_date %> to <%= booking.end_date %></p>
          <%= link_to "Edit Booking", edit_booking_path(booking), class: "btn btn-primary" %>
          <%= link_to "Cancel Booking", booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to cancel the booking?" }, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/carparks/edit.html.erb
<div class="container mt-5 pt-5">
	<div class="row justify-content-center">
		<h1 class="head text-center">Please edit your carpark</h1>
	</div>
	<hr>
	<div class="row justify-content-center">
		<div class="col-md-4 card-product-infos m-2" id="edit-carpark-form-container">
			<%= simple_form_for(@carpark) do |f| %>
        <div class="form-inputs">
        <%= f.input :address %>
          <%= f.input :length %>
          <%= f.input :width %>
          <%= f.input :height %>
					<%= f.input :rate_day %>
					<%= f.input :photo, placeholder: "Insert Photo Url" %>
			  </div>

			  <div class="form-actions">
			    <%= f.button :submit, :class => "btn btn-primary btn-lg btn-block"%>
			  </div>
			<% end %>
		</div>
	</div>
</div>
<br>
<%= link_to "Back To Carpark", carpark_path, class: "btn btn-primary btn-sm" %>

app/views/carparks/index.html.erb
<div
  id="map"
  style="width: 100%;
  height: 500px;
  box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
<div class="container">
  <div class="d-flex justify-content-center my-5">
    <% if @carparks.length > 0 %>
      <h1 class="display-4">All Carpark Listings</h1>
    <% else %>
      <h1 class="display-4">No  matching result for <%= params[:query].capitalize %> </h1>
    <% end %>
  </div>
    <div class="cards">
      <% @carparks.each do |carpark| %>
        <%= link_to carpark_path(carpark), :style => "text-decoration: none" ,:action => 'go' do %>
          <div class="card-category text-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= carpark.photo %>)"><%= carpark.address %>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/carparks/new.html.erb
<div class="container my-5 pt-5">
	<div class="row justify-content-center">
		<h1 class="head text-center my-3">Create your carpark listing</h1>
	</div>
	<div class="row justify-content-center">
		<div class="col-md-8 card-product-infos m-4 py-4" id="create-carpark-form-container">
			<%= simple_form_for(@carpark) do |f| %>
        <div class="form-inputs">
          <div class="col-md-8 mx-auto">
            <%= f.input :address, id: "carpark_address" %>
          </div>
          <div class="d-flex col-md-8 mx-auto">
            <%= f.input :length, placeholder: "in cm" %>
            <%= f.input :width, placeholder: "in cm" %>
            <%= f.input :height, placeholder: "in cm" %>
          </div>
          <div class="d-flex col-md-8 mx-auto">
            <div>
              <%= f.input :rate_day, class: "col-md-4", placeholder: "$" %>
              <%= f.input :photo, placeholder: "Insert Photo URL", class: "col-md-4" %>
            </div>
    			  <div class="form-actions my-auto d-flex align-items-end .align-content-end flex-column col-md-6">
    			    <%= f.button :submit, class: "btn btn-outline-success mt-5 py-3 px-4"%>
              <%= link_to "Back to Homepage", root_path, class: "btn btn-outline-success my-3 py-3" %>
    			  </div>
          </div>
			  </div>

			<% end %>
		</div>
	</div>
</div>
<br>

app/views/carparks/search.html.erb
<div
  id="map"
  style="width: 100%;
  height: 500px;
  box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
<div class="container">
  <div class="d-flex justify-content-center my-5">
    <% if @carparks.length > 0 %>
      <h1 class="display-4"><%= @carparks.length %> matching Carparks for <strong><%= params[:query] %></strong> within 10km</h1>
    <% else %>
      <h1 class="display-4">No  matching result for <%= params[:query].capitalize %> </h1>
    <% end %>
  </div>
    <div class="cards">
      <% @carparks.each do |carpark| %>
        <%= link_to carpark_path(carpark), :style => "text-decoration: none" ,:action => 'go' do %>
          <div class="card-category text-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= carpark.photo %>)"><%= carpark.address %>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/carparks/show.html.erb
<br>
<div class ="container mt-5 pt-5">
  <div class ="row">
    <div class="col-lg-8">
      <div class="card-trip">
      <img src=<%= @carpark.photo %>>
        <div class="card-trip-infos">
          <div>
            <h2><%=@carpark.address %></h2>
            <p>Length: <%=@carpark.length %>cm x Width: <%=@carpark.width %>cm x Height: <%=@carpark.height %>cm</p>
          </div>
          <h2 class="card-trip-pricing">Rate Per Day: $<%= @carpark.rate_day %></h2>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card-product-infos booking-form-card" id='carpark-booking-dates' data-unavailable="<%= @carpark.unavailable_dates.to_json %>">
        <%= simple_form_for [@carpark, @booking] do |f| %>
          <h3 class="pt-3">Booking:</h3>
          <%= f.input :start_date, as: :string, type: :text, class: "form-control", placeholder: "Select your start date" %>
          <%= f.input :end_date, as: :string, type: :text, class: "form-control", placeholder: "Select your end date" %>
          <% if user_signed_in? %>
            <% if current_user.id != @carpark.user_id  %>
              <%= f.submit "Reserve now", class: "btn btn-outline-success mt-5"%>
            <% else %>
              <%= link_to "My Dashboard", bookings_path, class: "btn btn-outline-success mt-5" %>
            <% end %>
          <% else %>
            <%= f.submit "Reserve now", class: "btn btn-outline-success mt-5"%>
          <% end %>
        <% end %>
      </div>
    </div>
    </div>
  <br>
  <div>
    <% if user_signed_in? %>
      <% if current_user.id == @carpark.user_id  %>
        <%= link_to "Edit Carpark", edit_carpark_path(@carpark), class: "btn btn-primary btn-sm" %>
      <% end %>
    <% end %>
    </div>
      <%= link_to "Back To All Carparks", carparks_path, class: "btn btn-primary btn-sm" %>
    </div>
  <div>
</div>
<br>
<div class ="container">
  <% @reviews.each do |review| %>
  <div class="card mb-3 bg-light col-8">
    <div class="card-header">
      Review by: <%= review.booking.user.email %>
    </div>
    <div class="card-body">
      <h5 class="card-title">Review Score: <%= review.rating %></h5>
      <p class="card-text"><%= review.content %></p>
    </div>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Parkonomy | Find Parking Economically</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="flex-wrapper">
      <%= render 'shared/navbar' %>
      <%= yield %>
      <%= render 'shared/flashes' %>

      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      <div class="footer-copyright">
        by csvonrails @ Le Wagon #306
    </div>
    <!-- Load Javascript file last -->
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-lg-8 col-sm-12">
        <div class="card-search">
          <div class="card-search-body">
            <h1 class="card-title">I'm looking for a carpark in</h1>
<!--             <p class="card-text mb-3">Find second home for your car, wherever you are, in Singapore.</p>

            <%#= form_tag("/search", method: "get") do %>
              <%#= label_tag(:query, "Address:", class: "col-form-label-lg") %>
              <%#= text_field_tag(:query, "", id: "search_address", class: "form-control mb-sm-2") %>
              <%#= label_tag(:date, "From:", class: "col-form-label") %>
              <%#= date_field(:date, :start_date, value: Date.today, class: "form-control mb-sm-2") %>
              <%#= label_tag(:date, "Until:", class: "col-form-label") %>
              <%#= date_field(:date, :end_date, value: (Date.today + 2.week), class: "form-control mb-sm-2") %>
              <%#= submit_tag("Search", class: "btn btn-outline-success mt-4") %>
            <%# end %> -->
              <%= form_tag("/search", method: "get", id: "home_form", class: "my-5 text-center px-5" ) do %>
                    <%= text_field_tag(:query, "", id: "search_address", placeholder: "", class: "search-title form-control text-white p-5") %>
                  <div class="d-flex">
                    <%= date_field(:date, :start_date, value: Date.today, class: "form-control text-white mb-sm-2") %>
                    <%= date_field(:date, :end_date, value: (Date.today + 2.week), class: "form-control text-white mb-sm-2") %>
                  </div>
                  <%#= submit_tag("Search", class: "btn btn-outline-success mt-4") %>
              <!-- </form> -->
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">

  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-car logo"></i>
    <!-- <span id="app_name">Parkonomy</span> -->
    <%#= image_tag "logo_ver2.png", alt: "Parkonomy", class: "logo"%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
<!--         <li class="nav-item active">
          <%#= link_to "Search carpark", root_path, class: "nav-link" %>
        </li> -->
        <li class="nav-item">
          <%= link_to "Dashboard", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Make a booking", "/", class: "dropdown-item" %>
            <%= link_to "Rent out your carpark", "/carparks/new", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-white btn-gradient", id: "login-btn" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>